namespace Elenigma.Main
{
    public enum GameView
    {
        ConversationScene_ConversationView,
        ConversationScene_ConversationView2,
        ConversationScene_ConversationView3,
        ConversationScene_SelectionView,
        CreditsScene_CreditsView,
        IntroScene_IntroView,
        TitleScene_ContinueView,
        TitleScene_SettingsView,
        TitleScene_TitleView,

        None = -1
    }

    public enum GameSound
    {
        a_mainmenuconfirm,
        a_mainmenuselection,
        Back,
        BattleStart,
        Blip,
        Bonk,
        Bounce,
        Chest,
        Claw,
        Confirm,
        Construct,
        Counter,
        Cure,
        Cursor,
        dialogue_auto_scroll,
        Drop,
        Encounter,
        EnemyDeath,
        Error,
        Eruption,
        Fire,
        Fireball,
        footsteps_dirt_1,
        footsteps_dirt_2,
        footsteps_dirt_3,
        footsteps_dirt_4,
        footsteps_grass_1,
        footsteps_grass_2,
        footsteps_grass_3,
        footsteps_grass_4,
        Freeze,
        GetItem,
        Heal,
        Ice,
        Laser,
        LevelUp,
        menu_cursor_change,
        menu_select,
        Miss,
        move_selection_cursor,
        Pickup,
        Ready,
        Rest,
        Savepoint,
        Screech,
        Selection,
        Skeleton,
        Slash,
        Talk,
        Thunder,

        None = -1
    }

    public enum GameMusic
    {
        Awakening,
        Elenigma,
        Home,
        BeyondtheHills,
        BlastingThroughtheSky,
        ChoiceEncounter,
        ExploringtheDepths,
        FireStreaming,
        NewDestinations,
        Sanctuary,
        Selection,

        None = -1
    }

    public enum GameData
    {
        ConversationData,

        None = -1
    }

    public enum GameShader
    {
        BattleEnemy,
        BattleIntro,
        BattlePlayer,
        ColorFade,
        DayNight,
        Default,
        HeatDistortion,
        Pinwheel,
        Portrait,

        None = -1
    }

    public enum GameSprite
    {
        Ailments,
        Clouds,
        Down,
        DownSelected,
        Enter,
        Gamepad,
        Keyboard,
        Target,
        Title,
        TurningBook,
        Up,
        UpSelected,
        Actors_AdultMC,
        Actors_Blank,
        Actors_Cat,
        Actors_Chest,
        Actors_Dad,
        Actors_DogFamiliar,
        Actors_DroneShadow,
        Actors_HumanFamiliar,
        Actors_Mom,
        Actors_NPCs,
        Actors_Rival,
        Actors_Sis,
        Actors_Slyph,
        Actors_Sword,
        Actors_Townie2,
        Actors_Townie3,
        Actors_Townie4,
        Actors_Twinkle,
        Actors_Undine,
        Actors_WaterMC,
        Actors_WindMC,
        Actors_YoungMC,
        Background_Blank,
        Background_Splash,
        Background_Title,
        Particles_Exclamation,
        Particles_Gust,
        Particles_Smoke,
        Portraits_AdultMC,
        Portraits_DarkGoddess,
        Portraits_DivineBeast,
        Portraits_DogFamiliar,
        Portraits_HumanFamiliar,
        Portraits_LightGod,
        Portraits_Regions,
        Portraits_Slyph,
        Portraits_Undine,
        Portraits_YoungMC,
        Tiles_GroundTiles,
        Tiles_TownHouses1,
        Widgets_BattleFrame,
        Widgets_BattleWindow,
        Widgets_Blank,
        Widgets_ChatBoxes,
        Widgets_ClassicFrame,
        Widgets_ClassicWindow,
        Widgets_Convobox,
        Widgets_DarkFrame,
        Widgets_LabelGlow,
        Widgets_LightFrame,
        Widgets_MagicFrame,
        Widgets_MagicFrameSelected,
        Widgets_MagicLabel,
        Widgets_MagicSelected,
        Widgets_MagicWindow,
        Widgets_MonFrame,
        Widgets_MonSelected,
        Widgets_PartyLead,
        Widgets_PokeFrame,
        Widgets_PokeFrameSelected,
        Widgets_PortraitFrame,
        Widgets_SelectedFrame,
        Widgets_SmallConvo,
        Widgets_TechFrame,
        Widgets_TechFrameSelected,
        Widgets_TechGlow,
        Widgets_TechLabel,
        Widgets_TechSelected,
        Widgets_TechWindow,
        Background_Eclipse_Eclipse0,
        Widgets_Buttons_ClearPanel,
        Widgets_Buttons_GamePanel,
        Widgets_Buttons_GamePanelOpaque,
        Widgets_Buttons_GamePanelSelected,
        Widgets_Buttons_Panel,
        Widgets_Buttons_SelectedPanel,
        Widgets_Buttons_Technology,
        Widgets_Gauges_HealthBar,
        Widgets_Gauges_TechGauge,
        Widgets_Gauges_TechGaugeBackground,
        Widgets_Gauges_TechGaugeBar,
        Widgets_Gauges_TechSlider,
        Widgets_Icons_Armor,
        Widgets_Icons_AutoRevive,
        Widgets_Icons_Axe,
        Widgets_Icons_Blank,
        Widgets_Icons_Bow,
        Widgets_Icons_Bracelet,
        Widgets_Icons_Chest,
        Widgets_Icons_Club,
        Widgets_Icons_Dark,
        Widgets_Icons_Fire,
        Widgets_Icons_Greatsword,
        Widgets_Icons_Holy,
        Widgets_Icons_Ice,
        Widgets_Icons_Icons,
        Widgets_Icons_Mace,
        Widgets_Icons_Necklace,
        Widgets_Icons_None,
        Widgets_Icons_Potion,
        Widgets_Icons_Robe,
        Widgets_Icons_Shield,
        Widgets_Icons_Slyph,
        Widgets_Icons_Staff,
        Widgets_Icons_Sword,
        Widgets_Icons_Tome,
        Widgets_Icons_Undine,
        Widgets_Icons_Vest,
        Widgets_Images_Pointer,
        Widgets_Images_Proceed,
        Widgets_Images_Settings,
        Widgets_Textplate_ClearPanel,
        Widgets_Textplate_Panel,
        Widgets_Windows_ClearPanel,
        Widgets_Windows_Panel,

        None = -1
    }

    public enum GameMap
    {
        SecretMeadow,
        TechWorldIntro,

        None = -1
    }

}
